### ISSUE TITLE
zerotier-one package downloads, but claims file does not exist

### ISSUE THREAD

**Issue by sorvani** [mkevenaar/chocolatey-packages#247] opened 2024-06-30 04:43 UTC
when installing zerotier-one the package downloads and the msi downloads. but i receive this error
```
PS C:\Users\sorvani> choco install zerotier-one -y
Chocolatey v2.3.0
Installing the following packages:
zerotier-one
By installing, you accept licenses for the packages.
Downloading package from source 'https://community.chocolatey.org/api/v2/'
Progress: Downloading zerotier-one 1.14.0... 100%

zerotier-one v1.14.0 [Approved]
zerotier-one package files install completed. Performing other installation steps.
Installing zerotier-one...
WARNING: MSI could not be found - it is possibly corrupt or not an MSI at all. If it was downloaded and the MSI is less than 30K, try opening it in an editor like Notepad++ as it is likely HTML. This is most likely an issue with the 'zerotier-one' package and not with Chocolatey itself. Please follow up with the package maintainer(s) directly.
ERROR: Running ["C:\Windows\System32\msiexec.exe" /i "C:\ProgramData\chocolatey\lib\zerotier-one\tools\ZeroTier%20One.msi" /qn /norestart /l*v "C:\Users\bnaadmin\AppData\Local\Temp\chocolatey\zerotier-one.1.14.0.log"] was not successful. Exit code was '1619'. Exit code indicates the following: MSI could not be found - it is possibly corrupt or not an MSI at all. If it was downloaded and the MSI is less than 30K, try opening it in an editor like Notepad++ as it is likely HTML. This is most likely an issue with the 'zerotier-one' package and not with Chocolatey itself. Please follow up with the package maintainer(s) directly..
The install of zerotier-one was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\zerotier-one\tools\chocolateyinstall.ps1'.
 See log for details.
Unable to move directory 'C:\ProgramData\chocolatey\lib\zerotier-one':
 (5) Access is denied: [\\?\C:\ProgramData\chocolatey\lib-bad\zerotier-one\1.14.0]
Retrying by moving individual files

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - zerotier-one (exited 1619) - Error while running 'C:\ProgramData\chocolatey\lib\zerotier-one\tools\chocolateyinstall.ps1'.
 See log for details.
```
removing the `-y` switch and looking at the package donlaoded, i see this: `file          = "$toolsDir\ZeroTier%20One.msi"`
Because the path name is quoted, the %20 is not parsed as a space.
I changed the downloaded package to this: `file          = "$toolsDir\ZeroTier One.msi"`
and then hit `Y` on the install prompt and it successfully installed.

**Comment by sorvani** [comment] 2024-06-30 04:53
looking at the file in the repo here, it does not have the `%20`, there is no space at all. it is `ZeroTierOne.msi` which is also not correct for the current donload file version.
https://github.com/mkevenaar/chocolatey-packages/blob/master/automatic/zerotier-one/tools/chocolateyinstall.ps1

**Comment by sorvani** [comment] 2024-06-30 05:50
looking at the commit history, i see it was just changed to remove the `%20` in the commit 68f6207. But looking at the source for the files, that will break anyone who needs to pull a version prior to 1.1.12.
https://download.zerotier.com/RELEASES/1.1.10/dist/ has no `ZeroTierOne.msi`, only `ZeroTier One.msi`

**Comment by nerdbaggy** [comment] 2024-07-10 14:23
Having the same issue #240 did fix it as well

**Comment by mkevenaar** [comment] 2024-07-10 14:56
Duplicate of #240

This will be fixed in the next release of ZeroTier-One

**Closed by mkevenaar** 2024-07-10 14:56 UTC
